### PR TITLE
TDP Happy Halloween

### PR DESCRIPTION
**Pull request by danyi**
add AOKZOE A1 AR07
air can to max max max （You might need to be at the North Pole）
Happy Halloween

### CODE REVIEW

**Comment by pastaq** [comment]
I'm not sure I'm comfortable with changing the max boost to such high levels. This changes the slowPPT value above any value that has been safely confirmed stable on those chips. I like to maintain reasonable defaults in the code that's widely distributed to end users to avoid issues with bad user experience and device damage. Advanced users can edit these on their own machines as desired.

Also, if changes are made for device specific alterations, they should be in separate PR's for each device so inclusion of one isn't held back by another if changes are required. This also helps in reverting bad commits later if needed as it reduces the amount of code validation later.

**Comment by danyi** [comment]
I will change to the corresponding model later

ayanoe they gave me an air to test

AIR's official limit is 65 degrees

So there's no way you can pull over that limit

This is just a Halloween joke

**Comment by danyi** [comment]
How do I use your plugin on Chimera OS

**Comment by pastaq** [comment]
Follow the instructions in the README on this project's home page. If you're using the beta steam client you'll need to revert to the standard steam client as Valve introduced some changes that broke Crankshaft and decky-loader a while back and we're still waiting on the Crankshaft dev to push a fix.

**Pull request closed without merging**
